version: '3.8'

services:
  kitsu-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitsu-client
    restart: always
    ports:
      - "4888:3000"
    environment:
      - KITSU_API_URL=http://192.168.1.60:3002/api
      - KITSU_EMAIL=plutobase@flyingpluto.ai
      - KITSU_PASSWORD=Styx@001
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
