version: '3.8'

services:
  kitsu-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitsu-client
    restart: always
    ports:
      - "4888:4888"
    environment:
      - KITSU_API_URL=http://172.17.0.1:3002/api
      - KITSU_EMAIL=plutobase@flyingpluto.ai
      - KITSU_PASSWORD=Styx@001
      - NODE_ENV=production
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiN2RhYWI0YmY0Zjc3MTRkNzBiMjFjYjQyN2U1NzU0ZWYiLCJ0IjoiNjFkZTUxNjktMGY2OC00ZDAzLTgxZjUtOWExNTg1ZGU5OTU0IiwicyI6IlpEa3hZV0kxTW1NdE1UUm1aaTAwTUdZekxXSmxZV1l0TlRkallqWTJZbVZsTVRNeCJ9
    depends_on:
      - kitsu-client
